# Generated by Django 5.1.7 on 2025-04-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0002_attribute_attributevalue_comment_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
